### ISSUE TITLE
Sending Money Issues

### ISSUE THREAD

**Issue by NigelBarnes** [220725-JavaFS/tgh-financial-frontend#67]
- When sending money to another User, if the amount is invalid (0 or negative), there is no error message to let the user know that’s the issue. 
-  You can send money to yourself.
-  If the Account Id is wrong on the send money component, there is no error message to indicate that it is wrong.

**Comment by BlizWoRo** [comment]
Team SendMoneyBugFix will work on it.

**Comment by HunterKelly** [comment]
Added error message with invalid amount. 
Added error message and validation so you can not send money to the same account.
If account ID is wrong in the send money component, there is now an error message to indicate that it doesn't exist.

Pull request created from sendMoneyBugFix branch
